console.log("Hello, World!");
console.log('1');
console.log(2);
console.log('3');
console.log(25);
console.log(25.5);
console.log(25.5 + 25.5);
console.log("abc" + "def");
console.log();
console.log("");